create extension if not exists pgcrypto;

create table if not exists public.store_products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12, 2) not null default 0,
  category text not null default '',
  image text not null default '',
  stock integer not null default 0,
  featured boolean not null default false,
  description text not null default '',
  fulfillment_type text not null default 'inhouse' check (fulfillment_type in ('inhouse', 'dropship')),
  supplier_name text not null default '',
  supplier_sku text not null default '',
  supplier_cost numeric(12, 2) not null default 0,
  supplier_link text not null default '',
  processing_time text not null default '',
  shipping_time text not null default '',
  sale_enabled boolean not null default false,
  sale_price numeric(12, 2) not null default 0,
  sale_label text not null default 'Sale',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.social_posts (
  id uuid primary key default gen_random_uuid(),
  actor_id text not null,
  user_id uuid references auth.users (id) on delete set null,
  display_name text not null,
  user_name text not null default '',
  avatar text not null default 'SE',
  channel text not null default 'all',
  media_type text not null default 'image' check (media_type in ('image', 'video')),
  media_url text not null default '',
  caption_title text not null default '',
  caption_text text not null default '',
  tags jsonb not null default '[]'::jsonb,
  match_title text not null default 'Seen in this post',
  promote_enabled boolean not null default false,
  promoted_title text not null default '',
  promoted_price text not null default '',
  promoted_text text not null default '',
  likes_count integer not null default 0,
  comments_count integer not null default 0,
  saves_count integer not null default 0,
  like_actor_ids jsonb not null default '[]'::jsonb,
  like_actors jsonb not null default '[]'::jsonb,
  save_actor_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.social_post_comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.social_posts (id) on delete cascade,
  parent_comment_id uuid references public.social_post_comments (id) on delete cascade,
  actor_id text not null,
  user_id uuid references auth.users (id) on delete set null,
  author_name text not null,
  user_name text not null default '',
  avatar text not null default 'SE',
  body text not null,
  likes_count integer not null default 0,
  like_actor_ids jsonb not null default '[]'::jsonb,
  like_actors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.social_posts
  add column if not exists channel text not null default 'all';

create table if not exists public.support_workspace_threads (
  thread_id text primary key,
  assigned_rep text not null default '',
  status text not null default 'open',
  notes text not null default '',
  customer_email text not null default '',
  subject text not null default '',
  updated_at timestamptz not null default timezone('utc', now()),
  updated_by text not null default ''
);

create index if not exists store_products_featured_idx
  on public.store_products (featured, category);

create index if not exists social_posts_actor_id_idx
  on public.social_posts (actor_id, created_at desc);

create index if not exists social_posts_user_id_idx
  on public.social_posts (user_id, created_at desc);

create index if not exists social_post_comments_post_id_idx
  on public.social_post_comments (post_id, created_at);

create or replace function public.set_socialera_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.sync_social_post_reactions(
  p_post_id uuid,
  p_likes_count integer default 0,
  p_like_actor_ids jsonb default '[]'::jsonb,
  p_like_actors jsonb default '[]'::jsonb,
  p_saves_count integer default 0,
  p_save_actor_ids jsonb default '[]'::jsonb
)
returns public.social_posts
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.social_posts;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.social_posts
  set
    likes_count = greatest(coalesce(p_likes_count, 0), 0),
    like_actor_ids = case when jsonb_typeof(coalesce(p_like_actor_ids, '[]'::jsonb)) = 'array' then coalesce(p_like_actor_ids, '[]'::jsonb) else '[]'::jsonb end,
    like_actors = case when jsonb_typeof(coalesce(p_like_actors, '[]'::jsonb)) = 'array' then coalesce(p_like_actors, '[]'::jsonb) else '[]'::jsonb end,
    saves_count = greatest(coalesce(p_saves_count, 0), 0),
    save_actor_ids = case when jsonb_typeof(coalesce(p_save_actor_ids, '[]'::jsonb)) = 'array' then coalesce(p_save_actor_ids, '[]'::jsonb) else '[]'::jsonb end
  where id = p_post_id
  returning * into updated_row;

  if updated_row.id is null then
    raise exception 'Social post not found';
  end if;

  return updated_row;
end;
$$;

create or replace function public.sync_social_comment_reactions(
  p_comment_id uuid,
  p_likes_count integer default 0,
  p_like_actor_ids jsonb default '[]'::jsonb,
  p_like_actors jsonb default '[]'::jsonb
)
returns public.social_post_comments
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.social_post_comments;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  update public.social_post_comments
  set
    likes_count = greatest(coalesce(p_likes_count, 0), 0),
    like_actor_ids = case when jsonb_typeof(coalesce(p_like_actor_ids, '[]'::jsonb)) = 'array' then coalesce(p_like_actor_ids, '[]'::jsonb) else '[]'::jsonb end,
    like_actors = case when jsonb_typeof(coalesce(p_like_actors, '[]'::jsonb)) = 'array' then coalesce(p_like_actors, '[]'::jsonb) else '[]'::jsonb end
  where id = p_comment_id
  returning * into updated_row;

  if updated_row.id is null then
    raise exception 'Social comment not found';
  end if;

  return updated_row;
end;
$$;

drop trigger if exists store_products_set_updated_at on public.store_products;
create trigger store_products_set_updated_at
before update on public.store_products
for each row
execute function public.set_socialera_updated_at();

drop trigger if exists social_posts_set_updated_at on public.social_posts;
create trigger social_posts_set_updated_at
before update on public.social_posts
for each row
execute function public.set_socialera_updated_at();

drop trigger if exists social_post_comments_set_updated_at on public.social_post_comments;
create trigger social_post_comments_set_updated_at
before update on public.social_post_comments
for each row
execute function public.set_socialera_updated_at();

alter table public.store_products enable row level security;
alter table public.social_posts enable row level security;
alter table public.social_post_comments enable row level security;
alter table public.support_workspace_threads enable row level security;

drop policy if exists "store_products_select_public" on public.store_products;
create policy "store_products_select_public"
on public.store_products
for select
to anon, authenticated
using (true);

drop policy if exists "social_posts_select_public" on public.social_posts;
create policy "social_posts_select_public"
on public.social_posts
for select
to anon, authenticated
using (true);

drop policy if exists "social_post_comments_select_public" on public.social_post_comments;
create policy "social_post_comments_select_public"
on public.social_post_comments
for select
to anon, authenticated
using (true);

drop policy if exists "social_posts_insert_authenticated" on public.social_posts;
create policy "social_posts_insert_authenticated"
on public.social_posts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "social_post_comments_insert_authenticated" on public.social_post_comments;
create policy "social_post_comments_insert_authenticated"
on public.social_post_comments
for insert
to authenticated
with check (auth.uid() = user_id);

grant execute on function public.sync_social_post_reactions(uuid, integer, jsonb, jsonb, integer, jsonb) to authenticated;
grant execute on function public.sync_social_comment_reactions(uuid, integer, jsonb, jsonb) to authenticated;
